# Generated by Django 6.0.4 on 2026-04-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('AUTHOR', 'Author'), ('USER', 'User')], default='USER', max_length=10),
        ),
    ]
